apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patchesJson6902:
- target:
    kind: Deployment
    name: whereami
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/image
      value: northamerica-northeast1-docker.pkg.dev/acm-workshop-618-tenant/containers/whereami:v1.2.14
- target:
    kind: VirtualService
    name: whereami
  patch: |-
    - op: replace
      path: /spec/hosts
      value:
        - whereami.endpoints.acm-workshop-618-tenant.cloud.goog
